### ISSUE TITLE
代码文件有点大

### ISSUE THREAD

**Issue by gocnpan** [toeii/FlutterExampleApp_ExtensionRead#1]

**Comment by toeii** [comment]
可以删掉images目录下用不到的示例资源

**Comment by toeii** [comment]
> _No description provided._

可以删掉images目录下用不到的示例资源

**Comment by gocnpan** [comment]
> > _No description provided._
> 
> 可以删掉images目录下用不到的示例资源

应该不止是images目录下的示例图片，images目录我看了下大概18m左右，我现在下载20%有78m

**Comment by toeii** [comment]
> > > _No description provided._
> > 
> > 
> > 可以删掉images目录下用不到的示例资源
> 
> 应该不止是images目录下的示例图片，images目录我看了下大概18m左右，我现在下载20%有78m

谢谢你的反馈，这个问题修复了。。build目录文件沉淀的关系，“flutter clean”就OK了

**Comment by gocnpan** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > 可以删掉images目录下用不到的示例资源
> > 
> > 
> > 应该不止是images目录下的示例图片，images目录我看了下大概18m左右，我现在下载20%有78m
> 
> 谢谢你的反馈，这个问题修复了。。build目录文件沉淀的关系，“flutter clean”就OK了

不客气，谢谢大神提供的项目，让我有机会参考学习
